#!/bin/bash
### BEGIN INIT INFO
# Provides: haldor
# Required-Start: $local_fs $network
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: haldor
# Description: haldor the hal door daemon
### END INIT INFO
# Haldor init script

#/home/haldor/haldor/start.sh "$@"
sudo -H -u haldor bash -c "/home/haldor/haldor/start.sh \"$@\""
